# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: sidestickies
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: sidestickies
mimetype: ''
mimetype_name: ''
project_short_description: Sidestickies Jupyter Extension
python_name: nbtags
repository: https://github.com/NII-cloud-operation/sidestickies
test: true
viewer_name: ''

